name: hz_loading_screen
description: A customizable and easy-to-use Flutter package for displaying overlay loading screens that can be accessed from anywhere in your app. Perfect for network requests, file operations, and time-consuming tasks.
version: 0.0.1
homepage: https://github.com/hassan171/hz_loading_screen
repository: https://github.com/hassan171/hz_loading_screen
issue_tracker: https://github.com/hassan171/hz_loading_screen/issues
documentation: https://github.com/hassan171/hz_loading_screen#readme

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
